### ISSUE TITLE
[Suggestion] set command reward can reward all player

### ISSUE THREAD

**Issue by tygh78071388** [steve4744/TNTRun#101]
I want player can get participation award.

Could you please add this feature? THX!

**Comment by steve4744** [comment]
You could run a command when the game starts to achieve this. In the arena config, set `commandOnStart` to an appropriate command to reward each player. You can use the `%PLAYER%` placeholder with a money or command reward. Any reward placed in the player's inventory will get removed at the end of the game, so is not suitable for rewarding items.

Alternatively there is the `TNTRun_reloaded_Timed_Rewards` plugin which can reward the players when the game starts and/or at intervals throughout the game.

**Comment by tygh78071388** [comment]
> You could run a command when the game starts to achieve this. In the arena config, set `commandOnStart` to an appropriate command to reward each player. You can use the `%PLAYER%` placeholder with a money or command reward. Any reward placed in the player's inventory will get removed at the end of the game, so is not suitable for rewarding items.
> 
> Alternatively there is the `TNTRun_reloaded_Timed_Rewards` plugin which can reward the players when the game starts and/or at intervals throughout the game.

THX!  Turns out it was using %PLAYER%   I Always use {PLAYER}

commandOnStop is triggered whenever a player leaves a game, regardless of whether the game has been started. not as expected

So I followed your advice anyway and used commandOnStart. XD
