### ISSUE TITLE
RGB dont work

### ISSUE THREAD

**Issue by 44wrw44** [steve4744/TNTRun#107]
![image](https://github.com/steve4744/TNTRun/assets/73754757/b94a8e81-4fe2-4de6-bf11-8e49ce478322)
![image](https://github.com/steve4744/TNTRun/assets/73754757/6bb0c4fd-acc8-435e-a867-6fd5c0dcef96)

**Comment by steve4744** [comment]
RGB colours for scoreboard entries are not supported in the Bukkit API. The scoreboard _header_ can be set using RGB colours as can all other config entries and messages that support colour codes. I've updated the wiki with more info on this: [https://github.com/steve4744/TNTRun/wiki/Scoreboard](url)

**Comment by 44wrw44** [comment]
Then can you add rgb support from the TAB plugin? 
Or display data from the scoreboard into a separate PlaceHolder?

> RGB colours for scoreboard entries are not supported in the Bukkit API. The scoreboard _header_ can be set using RGB colours as can all other config entries and messages that support colour codes. I've updated the wiki with more info on this: [https://github.com/steve4744/TNTRun/wiki/Scoreboard](url)

**Comment by 44wrw44** [comment]
I solved the problem by replacing &x&F&F&9&9&0&0 with §x§F§F§9§9§0§0.
Add to Wiki that you can use RGB via §x§r§r§g§g§b§b
