### ISSUE TITLE
Deluxe Hub To Tntrun Join Direct Problem

### ISSUE THREAD

**Issue by SmYt-INDIA** [steve4744/TNTRun#108]
Hello I am SmYt_IND,
I Added The command "tntrun join TNTRun" in the server select but not not joining the arena . But its is working Fine When a default member or ops does
Pls Help Me..

**Comment by steve4744** [comment]
probably you don't have permission `tntrun.join`
Can't think what else it would be without more details.

**Comment by SmYt-INDIA** [comment]
I mean its works when im using or any default members uses the command.
but when i added the command in serverselector its dosent work . Here is this-

# Server Selector GUI
# The ID of this inventory is 'serverselector' which you can open using the [MENU] action (e.g. "[MENU] serverselector").
# You can create more custom GUIs, just copy this entire file and paste a new one in the menus directory. The name of the file is the menu ID.
#
# PLAYER HEADS
#   You can have player heads, using player names, base64 or HeadDatabase IDs.
#   Examples
#     Username (must have logged into the server once)
#       material: PLAYER_HEAD
#       username: <name>
#
#     Base64
#       material: PLAYER_HEAD
#       base64: <base64 id>
#
#     HeadDatabase
#       material: PLAYER_HEAD
#       hdb: <hdb id>
#
# ITEM FLAGS
#   You can add flags to the item (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html)
#   Example:
#     item_flags:
#       - HIDE_ATTRIBUTES
#       - HIDE_DESTROYS
#       - HIDE_ENCHANTS
#       - HIDE_PLACED_ON
#       - HIDE_POTION_EFFECTS
#       - HIDE_UNBREAKABLE
#
# ITEM ACTIONS
#   All item actions can be found here https://wiki.lewisdev.fun/free-resources/deluxehub/action-types

# Slots of the GUI
slots: 27

# Title of the GUI
title: "Server Selector"

# Automatically update open inventories.
# This can be used to update placeholders in the GUI.
refresh:
  enabled: false
  rate: 40

# The items inside the GUI can be listed here
items:
  filler:
    material: GRAY_STAINED_GLASS_PANE
    slot: -1 # Setting the slot to -1 will fill every empty slot, you can also do "slots: [0, 1, 2]"
  factions:
    material: IRON_SWORD
    slot: 10
    amount: 1
    glow: true
    display_name: '&eKit PvP'
    lore:
      - '&7Online &a: &6%world_players_kitpvp%'
      - '&aClick To Join!!'
    actions:
      - '[CLOSE]'
      - '[MESSAGE] &7Sending you to: &eKit PvP'
      - '[CONSOLE] mvtp %player% kitpvp'
      # For multi-world servers using Multiverse-Core, use the action:
      # - '[CONSOLE] mvtp %player% world'
  survival:
    material: GRASS_BLOCK
    slot: 12
    amount: 1
    glow: false
    display_name: '&cSurvival'
    lore:
      - '&7Online &a: &6%world_players_survival%'
      - '&aClick To Join!!'
    actions:
      - '[CLOSE]'
      - '[MESSAGE] &7Sending you to: &cSurvival'
      - '[CONSOLE] mvtp %player% survival'
  tntrun:
    material: TNT
    slot: 14
    amount: 1
    glow: false
    display_name: '&4TNT Run'
    lore:
      - '&7Online &a: &6%world_players_tntrun%'
      - '&aClick To Join!!'
    actions:
      - '[CLOSE]'
      - '[MESSAGE] &7Sending you to: &4tntrun'
      - '[CONSOLE] tntrun join TNTRun'
  skywars:
    material: DIAMOND_SWORD
    slot: 16
    amount: 1
    glow: false
    display_name: '&bSkyWars' 
    lore:
      - '&7Online &a: &6Coming Soon'
      - '&aClick To Join!!'
    actions:
      - '[CLOSE]'
      - '[MESSAGE] &7Coming Soon!!'

**Comment by SmYt-INDIA** [comment]
All of the things are working as well like mvtp but tntrun join cmd dosent work.

**Comment by steve4744** [comment]
In DeluxeHub's `serverselector.yml` you need to change the console command to use `trconsole` instead of `tntrun` and you need to specify the player as an argument, so assuming the arena is called TNTRun, the line would be
```
'[CONSOLE] trconsole join TNTRun %player%'
```

**Comment by SmYt-INDIA** [comment]
Ok Sir Thanks!!
