### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ThrowerWay** [steve4744/TNTRun#109]
Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

https://github.com/steve4744/TNTRun/blob/6d29bd524f709111120d7b0430e58cac779a7c2c/src/main/java/tntrun/eventhandler/ShopHandler.java#L40

**Comment by steve4744** [comment]
Thanks for raising this. The link you provide is for the Paper API while this plugin uses the Spigot API which doesn't seem to endorse using inventory holders in this way, see https://www.spigotmc.org/threads/what-is-the-inventoryholder-interface.342812

However I think the issue has now been resolved in commit 834f09c as we no longer use the title to check the inventory.
