### ISSUE TITLE
Translation for STATS.

### ISSUE THREAD

**Issue by TheIntelloBox** [steve4744/TNTRun#19]
Hey,

Could you add something to translate "Stats" ?

Thanks ! :D

**Comment by steve4744** [comment]
Hi, 

yes sure, I'll try to add it the next update.

Thanks

**Comment by steve4744** [comment]
This is included in commit 2f210fa

**Comment by TheIntelloBox** [comment]
How can I install the new version with this commit ?

**Comment by steve4744** [comment]
I've published a pre-release of v6.8 here where you can download the jar file, here:
https://github.com/steve4744/TNTRun/releases

Let me know if you find any issues with it.
