### ISSUE TITLE
1.13 compatible ?

### ISSUE THREAD

**Issue by TheIntelloBox** [steve4744/TNTRun#22]
Hey ! :D 

Could you update TNTRun for 1.13 ? :)

Thanks !

**Comment by steve4744** [comment]
Hi,
Yes it will be updated for 1.13. I intend to test it properly before releasing it, which means I'm dependent on at least WorldEdit to be updated, as this is needed to create arenas.
Thanks

**Comment by TheIntelloBox** [comment]
There are WorldEdit dev builds. :)

**Comment by steve4744** [comment]
If you mean the ones on enginhub.org they don't work on 1.13. If you have a link to a working dev build I'll be happy to try it?

**Comment by steve4744** [comment]
Yeah, I've tried the latest but it doesn't work. Some methods within WE have changed names so the selections aren't working. Probably not a big deal, but need time to look into it. :-(

**Comment by steve4744** [comment]
Issue with WorldEdit is resolved - just need to do some final testing.

**Comment by TheIntelloBox** [comment]
Hey,

Will you release the version this week ? :)

Thanks !

**Comment by steve4744** [comment]
Hi
I will release something this week. The plugin is dependent on WorldEdit 7 (it uses WE methods to set the arena bounds) which is still in development and receiving a major overhaul, Spigot 1.13 is in "extreme caution" stage, and Mojang will be releasing 1.13.1 imminently. So rushing out a release on Spigot is probably not the best idea. 
I have one more thing I want to test tomorrow, and then I'll make a pre-release jar available for download on GitHub. 
Thanks.

**Comment by steve4744** [comment]
https://github.com/steve4744/TNTRun/releases/tag/v7.0-beta

**Comment by TheIntelloBox** [comment]
Thanks, I'll tell you if I find bugs. :D

**Comment by steve4744** [comment]
..... and did you find any?

**Comment by steve4744** [comment]
I'll take that as a no.

**Comment by steve4744** [comment]
Closed as no reply for 4 weeks.
