### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by TheIntelloBox** [steve4744/TNTRun#23]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-1-development-builds.336415/

**Comment by steve4744** [comment]
I'm aware 1.13.1 is out. Just got back from holiday yesterday ... will release an update on Spigot in the next day or two.

**Comment by TheIntelloBox** [comment]
Does the latest version of the plugin (V7.0) support Minecraft 1.13.1 ? :D

**Comment by steve4744** [comment]
Yes it does

**Comment by steve4744** [comment]
Closed as 7.0 released on Spigot which supports 1.13.1.
