### ISSUE TITLE
Featherboard Scoreboard Duplicating Lines

### ISSUE THREAD

**Issue by Segysmundo** [steve4744/TNTRun#25]
We're using featherboard and once a game on tntrun ends and the players leave, the scoreboard duplicates the lines.

We're on Minecraft 1.12.2 using tntrun plugin version 6.8 and maybe it's happening too on the latest versions. (We're using featherboard latest version)

Before.
![23b19d3bd9dca9a2edbdf41b9cf8a598](https://user-images.githubusercontent.com/19178945/46919759-47450980-cfe4-11e8-8817-13d466643138.png)

After finishing a game.
![c0d256dcb919f6e36142dee42f6033b6](https://user-images.githubusercontent.com/19178945/46919739-e9182680-cfe3-11e8-8d03-56db63aec386.png)

**Comment by steve4744** [comment]
I don't have Featherboard so I can't test it directly myself. I've tested with QuickBoard and don't see duplicate lines.
It's possible I'm not removing the scoreboard cleanly in all cases - I'll review the code and see if there's anything I can do.
Thanks for reporting it.

**Comment by Segysmundo** [comment]
Yes sorry I forgot to mention it, I did set **UseScoreboard** to false and it still happens.

**Comment by steve4744** [comment]
Hi, 
I've created a v6.8.1 release that you can try.

https://github.com/steve4744/TNTRun/releases/tag/v6.8.1

This should hopefully get rid of the duplicate lines if you have `special: useScoreboard: false`.
You can try setting it to true (server reload needed) and see what happens, but without Featherboard to test it with I'm not able to say whether they are compatible or not.
Thanks.

**Comment by Segysmundo** [comment]
Seems like it's working perfectly now, no scoreboard duplication even with **UseScoreboard** set to true.

I'll keep an eye on it to see if any problems show up but it looks like it's been fixed. Thanks.

**Comment by steve4744** [comment]
Excellent - thanks for the update.
