### ISSUE TITLE
/trsetup setspawn {arena} broken

### ISSUE THREAD

**Issue by ChaseSantos** [steve4744/TNTRun#29]
Doesn't work, internal error 
https://pastebin.com/KN1tvHWN

**Comment by steve4744** [comment]
Thanks for the report - I'll attempt to recreate the issue, but any reason you are still using version 7.3 of the plugin? I would suggest downloading the latest versions of TNTRun_reloaded (v7.6) along with the latest WorldEdit and see if the problem persists.
Thanks.

**Comment by steve4744** [comment]
Ok I've managed to recreate this by running ```/trsetup setspawn [arena]``` before setting the bounds of the arena, so by running step 4 (see below) before step 2.

I still regard this as a bug as it should validate that the previous steps have been completed successfully. I'll fix this in v7.6.1.

Arena creation:
1. Give the arena a name

/trsetup create \<arena\>​

2. Set the boundary of the arena - using WorldEdit, select 2 opposite corners, one above and one below the arena, ensuring the whole of the arena is included within the selection.(http://wiki.sk89q.com/wiki/WorldEdit/Selection)

/trsetup setarena \<arena\>​

3. Set the lose level. This is basically the floor beneath the final level of the arena, the level at which the player loses. Use WorldEdit to select 2 points on opposite sides of the arena. The 2 points MUST be within the boundary of the arena from the previous step.

/trsetup setloselevel \<arena\>​

4. Set the spawnpoint. Go to the top level of the arena, the spawnpoint will be created at the location you are standing.

/trsetup setspawn \<arena\>​

5. Set spectator spawnpoint. The point at which a player spawns after losing (provided the game has not ended).

/trsetup setspectate \<arena\>​

6. Finish the arena creation and save it. The arena is automatically enabled.

/trsetup finish \<arena\>​

7. Set a main lobby location for all TNTRun arenas (only needs to be done once) at your current location.

/trsetup setlobby​

**Comment by ChaseSantos** [comment]
Yup, sorry about that. I am new to this github issue thing lol. I switch versions, didn't work on the latest, so I tried to go back to versions that had good reviews. Got it worked the way you said, thank you

**Comment by steve4744** [comment]
Ok great - thanks for the update.
It works in all versions btw, but the setup has to be done in the right order. In v7.6.1 extra validation will stop this error occurring.
