### ISSUE TITLE
FAWE support

### ISSUE THREAD

**Issue by CruelWinter2** [steve4744/TNTRun#30]
TNTRun does not support FAWE. Can you add FAWE support? My server is running spigot 1.13.

**Comment by steve4744** [comment]
Currently FAWE does not use the WorldEdit 7 API and is incompatible with plugins that require it.
Once FAWE is upgraded to use the WE7 API then I can look at supporting it. 
Thanks for the suggestion.

**Comment by steve4744** [comment]
There is now a version of FAWE which uses the WordEdit 7 API and so can be used with TNTRun_reloaded in place of the standard WordEdit 7 on Spigot 1.13.2.
https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/

Currently there is no FAWE for Spigot 1.14 afaik.

Closing this request.
