### ISSUE TITLE
Sign not working

### ISSUE THREAD

**Issue by edellenburg** [steve4744/TNTRun#33]
My players can not use sign to enter the arena. You can if you are opped. Can you help? Permissions are working for everything else

**Comment by steve4744** [comment]
Most likely reason is 'spawn protection'. Stop the server, set it to zero in the server.properties file, restart server.

**Comment by edellenburg** [comment]
thank you that worked. Love your plugin

**Comment by steve4744** [comment]
Excellent. Thank you.
