### ISSUE TITLE
Pom.xml 

### ISSUE THREAD

**Issue by AwesomestCode** [steve4744/TNTRun#41]
Please give info on how to compile in readme.md.

**Comment by steve4744** [comment]
I don't currently use Maven so there is no pom.xml file.
To compile the source just add the dependencies to the build path. The dependencies are listed on the Spigot page (https://www.spigotmc.org/resources/tntrun_reloaded-tntrun-for-1-13-1-15.53359/) with links to download each one.

I plan to add it Maven when I get some free time.

**Comment by steve4744** [comment]
Information has been added to the README.md.
