### ISSUE TITLE
An error has occurred while checking version!

### ISSUE THREAD

**Issue by LJIT-WD** [steve4744/TNTRun#42]
The plugin told me to report the issue:

> 13.02 10:42:00 [Server] INFO [10:42:00 INFO]: [TNTRun_reloaded] Checking plugin version...
> 13.02 10:42:00 [Server] INFO [10:42:00 INFO]: [TNTRun_reloaded] Failed to check for update on Spigot
> 13.02 10:42:00 [Server] INFO [10:42:00 WARN]: [TNTRun_reloaded] Plugin TNTRun_reloaded v6.8.2 generated an exception while executing task 23
> 13.02 10:42:00 [Server] INFO java.lang.NullPointerException: An error was occured while checking version! Please report this here: https://www.spigotmc.org/threads/tntrun_reloaded.303586/
> 13.02 10:42:00 [Server] INFO at tntrun.TNTRun$2.run(TNTRun.java:186) ~[?:?]
> 13.02 10:42:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paper-1.12.2.jar:git-Paper-1490]
> 13.02 10:42:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [paper-1.12.2.jar:git-Paper-1490]
> 13.02 10:42:00 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paper-1.12.2.jar:git-Paper-1490]
> 13.02 10:42:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
> 13.02 10:42:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
> 13.02 10:42:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

It seems that this error doesn't affect the plugin's performance on my server.

**Comment by steve4744** [comment]
Thanks for reporting the issue.
The simple "fix" for this is to turn off update checking in the config.yml
```
special:
  CheckForNewVersion: false
```
As the legacy version (v6.8.2) is not going to be updated, checking for an update is not really meaningful. 

The same issue for servers on 1.13-1.15.2 was fixed in v8.8 of the plugin.

I guess it should still be fixed, so will release v6.8.3 shortly.
