### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by SamIsOnMC** [steve4744/TNTRun#64]
Hey, so i have a glitch, i made the tntrun arena, set bungeecord to true; set the lobby to hub, restarted, and joined. It automatically says: You joined as a spectator
How to fix this?

**Comment by steve4744** [comment]
Hey, you need to explicitly set permission `tntrun.spectate: false` then you will join as a player.

**Comment by SamIsOnMC** [comment]
> 
> 
> Hey, you need to explicitly set permission `tntrun.spectate: false` then you will join as a player.

Hey! What about Staff who have OP?

**Comment by steve4744** [comment]
If the staff are allowed to join as players, they will need to have the permission explicitly set to false.  Anyone wanting to join as a spectator will need it set to true.

**Comment by steve4744** [comment]
Closing as information given.
