### ISSUE TITLE
Placeholders not working.

### ISSUE THREAD

**Issue by Aadi-mone** [steve4744/TNTRun#68]
Placeholders not working
![2021-11-04_13 42 04](https://user-images.githubusercontent.com/87631878/140287849-369f0dfa-a2b2-49ca-849c-1d553cdcb91d.png)

**Comment by steve4744** [comment]
Please follow the steps in the wiki
https://github.com/steve4744/TNTRun/wiki/Placeholders--Leaderboard-Checklist

**Comment by Aadi-mone** [comment]
that's for holograms?
I want it for a npc

**Comment by steve4744** [comment]
This is not the place to ask for support of NPC plugins. The wiki has "step-by-step" instructions on how to ensure tntrun placeholders work, and also how to set them up in holograms. If you require help with Citizens or some other plugin please speak to the appropriate dev team.
