### ISSUE TITLE
[Suggestion] Korean Translation.

### ISSUE THREAD

**Issue by hoehoetvhss** [steve4744/TNTRun#69]
I want to Translate Korean into your Plugin. To do that, Can you make a Polder with the name `ko` on it?

**Comment by steve4744** [comment]
Translations can be added using `gitlocalize`, and there is already  a 'ko' option available.

![image](https://user-images.githubusercontent.com/6975392/140901125-97725925-92e2-4edd-a1aa-c96e0569510d.png)

There are instructions on the wiki explaining how to add your translation through gitlocalize:
https://github.com/steve4744/TNTRun/wiki/Language-Support

If you prefer, you can send me the fully translated file and I will upload it to gitlocalize and include it in the next release.
Thanks.
