### ISSUE TITLE
Korean Language UnSupport.

### ISSUE THREAD

**Issue by hoehoetvhss** [steve4744/TNTRun#72]
Currently, GitHub has a Korean puller, but the latest version plug-in does not include Korean.

I wonder if you are currently developing Korean language support.

**Comment by steve4744** [comment]
The latest version was released on Oct 29th. Your Korean translation was supplied a week later so clearly can not be in the current version. The translation as you say has been merged on GitHub and will be included in the next release. 

I try to limit releases to no more than once per month as frequent updates can be annoying for server owners.  I expect v9.16 to be released in the next couple of weeks. This will include the Korean translation.

**Comment by hoehoetvhss** [comment]
Thank you for letting me know the development schedule and motto.

This will help players who want to use Korean.
