### ISSUE TITLE
Maven Dependency

### ISSUE THREAD

**Issue by mikenex10** [steve4744/TNTRun#82]

**Comment by mikenex10** [comment]
Hi there! Is Maven dependency enabled so that I can add TNTRun-reloaded a a dependence for my custom plugin in order to use your custom events? If so, where can I find it? Thank you so much!

**Comment by steve4744** [comment]
Hi, yes the details are here -  https://github.com/steve4744/TNTRun/wiki/Developer-Info

**Comment by mikenex10** [comment]
Yeah that is exactly what I neeeded! Thank you so much! Great support!
