### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by DaWinnerIsHere** [steve4744/TNTRun#97]
Hello, ive been running TNTRun_reloaded 9.20.0 on Paper 1.16.5 Java 16, and the placeholders for the plugin wont work in my hologram. There are players who have played the game and have stats to be added onto there, and ive followed the tutorial for holograms left on your spigot page. my HolographicDisplays is running on 2.4.7 and I have HolographicExtension and ProtocolLib installed. what's going on?

**Comment by steve4744** [comment]
If they've been created as per the examples for HD v2.4.x https://github.com/steve4744/TNTRun/wiki/Placeholders#holographicdisplays-v24x, then they should work ok.

What does the placeholder display in the hologram?

**Comment by DaWinnerIsHere** [comment]
![image](https://user-images.githubusercontent.com/71647641/186787345-0f26b6e9-cb19-46fd-9090-cd1e500ac172.png)
![image](https://user-images.githubusercontent.com/71647641/186787355-5e8a2731-ef65-4055-9ccf-1b3a95576fc6.png)
this is what displays in the hologram with the current config.

**Comment by steve4744** [comment]
Thanks. Looks like stats may be disabled. You can check by running `/tr stats`. If it is disabled check the server start up log for errors or a message telling you why its disabled.

**Comment by DaWinnerIsHere** [comment]
![image](https://user-images.githubusercontent.com/71647641/187052673-ec48b879-3bb5-4908-950b-86be0c7f8917.png)
Looks like its enabled

**Comment by steve4744** [comment]
![image](https://user-images.githubusercontent.com/6975392/187068625-a82bcf44-5046-4ac3-be44-74a7a618ef9c.png)

Check these from the wiki especially number 4 - if you've downloaded the expansion from papi ecloud then you need to remove it.

**Comment by DaWinnerIsHere** [comment]
![image](https://user-images.githubusercontent.com/71647641/187082275-5eb5e043-8a05-4d8e-9515-80a48b7f3bac.png)
looks like it works now, Thanks!
